app = "rsshub-leehskid"

[build]

[env]
  PORT = "1200"
  LISTEN_INADDR_ANY = "1"
  NODE_ENV = "production"

[http_service]
  internal_port = 1200
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  
  [[http_service.checks]]
    grace_period = "90s"  # 더 길게 설정
    interval = "30s"
    method = "GET"
    timeout = "10s"
    path = "/"
